### ISSUE TITLE
Expected Output

### ISSUE THREAD

**Issue by AnyhowStep** [jppzanetti/PQRTree#1]
```
public static void main(String[] args) throws IOException {
    PQRTree pqrtree = new PQRTree(6);
    System.out.println(pqrtree.toString());

    pqrtree.reduce(new int[] {0, 1});
    System.out.println(pqrtree.toString());
    pqrtree.reduce(new int[] {2, 3});
    System.out.println(pqrtree.toString());
    pqrtree.reduce(new int[] {3, 4});
    System.out.println(pqrtree.toString());
    pqrtree.reduce(new int[] {1, 5});
    System.out.println(pqrtree.toString());
    pqrtree.reduce(new int[] {1, 5});
    System.out.println(pqrtree.toString());
    pqrtree.reduce(new int[] {1, 2});
    System.out.println(pqrtree.toString());
}
```

```
(0 1 2 3 4 5)
(2 3 4 5 (0 1))
(4 5 (0 1) (2 3))
(5 (0 1) [4 3 2])
([5 1 0] [4 3 2])
([5 1 0] [4 3 2])
[5 2 3 4 ]
```

In the final output, `[5 2 3 4 ]`, you can see that there is a "space" after the `4`, meaning that `4` is not the last child. The last child is the leaf `0`, I believe.

However, it's not part of the output.

**Comment by jppzanetti** [comment]
Thank you for the report.

When merging the first child of a node into the LCA, the reference to the first child in the LCA node wasn't being updated. It should be fixed now.

The correct output for the last line should be `{4 3 2 5 1 0}` (or any permutation of these numbers, since it's an R-node.)
